// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ivapi.proto

package com.imperialvision.ivapi;

public interface IVApiResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.imperialvision.ivapi.IVApiResponse)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.imperialvision.ivapi.Output outputs = 1;</code>
     */
    java.util.List<Output>
    getOutputsList();

    /**
     * <code>repeated .com.imperialvision.ivapi.Output outputs = 1;</code>
     */
    Output getOutputs(int index);

    /**
     * <code>repeated .com.imperialvision.ivapi.Output outputs = 1;</code>
     */
    int getOutputsCount();

    /**
     * <code>repeated .com.imperialvision.ivapi.Output outputs = 1;</code>
     */
    java.util.List<? extends OutputOrBuilder>
    getOutputsOrBuilderList();

    /**
     * <code>repeated .com.imperialvision.ivapi.Output outputs = 1;</code>
     */
    OutputOrBuilder getOutputsOrBuilder(
            int index);

    /**
     * <code>int32 error_code = 2;</code>
     *
     * @return The errorCode.
     */
    int getErrorCode();

    /**
     * <code>string uuid = 3;</code>
     *
     * @return The uuid.
     */
    String getUuid();

    /**
     * <code>string uuid = 3;</code>
     *
     * @return The bytes for uuid.
     */
    com.google.protobuf.ByteString
    getUuidBytes();

    /**
     * <code>string begintime = 4;</code>
     *
     * @return The begintime.
     */
    String getBegintime();

    /**
     * <code>string begintime = 4;</code>
     *
     * @return The bytes for begintime.
     */
    com.google.protobuf.ByteString
    getBegintimeBytes();

    /**
     * <code>string endtime = 5;</code>
     *
     * @return The endtime.
     */
    String getEndtime();

    /**
     * <code>string endtime = 5;</code>
     *
     * @return The bytes for endtime.
     */
    com.google.protobuf.ByteString
    getEndtimeBytes();
}
