// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ivapi.proto

package com.imperialvision.ivapi;

public interface IVApiRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.imperialvision.ivapi.IVApiRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes bytes_img = 1;</code>
     *
     * @return The bytesImg.
     */
    com.google.protobuf.ByteString getBytesImg();

    /**
     * <code>string container = 2;</code>
     *
     * @return The container.
     */
    String getContainer();

    /**
     * <code>string container = 2;</code>
     *
     * @return The bytes for container.
     */
    com.google.protobuf.ByteString
    getContainerBytes();

    /**
     * <code>bytes bytes_json = 3;</code>
     *
     * @return The bytesJson.
     */
    com.google.protobuf.ByteString getBytesJson();

    /**
     * <code>string uuid = 4;</code>
     *
     * @return The uuid.
     */
    String getUuid();

    /**
     * <code>string uuid = 4;</code>
     *
     * @return The bytes for uuid.
     */
    com.google.protobuf.ByteString
    getUuidBytes();
}
