// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ivapi.proto

package com.imperialvision.ivapi;

/**
 * Protobuf type {@code com.imperialvision.ivapi.IVApiRequest}
 */
public final class IVApiRequest extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.imperialvision.ivapi.IVApiRequest)
        IVApiRequestOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use IVApiRequest.newBuilder() to construct.
    private IVApiRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private IVApiRequest() {
        bytesImg_ = com.google.protobuf.ByteString.EMPTY;
        container_ = "";
        bytesJson_ = com.google.protobuf.ByteString.EMPTY;
        uuid_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
            UnusedPrivateParameter unused) {
        return new IVApiRequest();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    private IVApiRequest(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    case 10: {

                        bytesImg_ = input.readBytes();
                        break;
                    }
                    case 18: {
                        String s = input.readStringRequireUtf8();

                        container_ = s;
                        break;
                    }
                    case 26: {

                        bytesJson_ = input.readBytes();
                        break;
                    }
                    case 34: {
                        String s = input.readStringRequireUtf8();

                        uuid_ = s;
                        break;
                    }
                    default: {
                        if (!parseUnknownField(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return Ivapi.internal_static_com_imperialvision_ivapi_IVApiRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
        return Ivapi.internal_static_com_imperialvision_ivapi_IVApiRequest_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        IVApiRequest.class, Builder.class);
    }

    public static final int BYTES_IMG_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString bytesImg_;

    /**
     * <code>bytes bytes_img = 1;</code>
     *
     * @return The bytesImg.
     */
    @Override
    public com.google.protobuf.ByteString getBytesImg() {
        return bytesImg_;
    }

    public static final int CONTAINER_FIELD_NUMBER = 2;
    private volatile Object container_;

    /**
     * <code>string container = 2;</code>
     *
     * @return The container.
     */
    @Override
    public String getContainer() {
        Object ref = container_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            container_ = s;
            return s;
        }
    }

    /**
     * <code>string container = 2;</code>
     *
     * @return The bytes for container.
     */
    @Override
    public com.google.protobuf.ByteString
    getContainerBytes() {
        Object ref = container_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            container_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int BYTES_JSON_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString bytesJson_;

    /**
     * <code>bytes bytes_json = 3;</code>
     *
     * @return The bytesJson.
     */
    @Override
    public com.google.protobuf.ByteString getBytesJson() {
        return bytesJson_;
    }

    public static final int UUID_FIELD_NUMBER = 4;
    private volatile Object uuid_;

    /**
     * <code>string uuid = 4;</code>
     *
     * @return The uuid.
     */
    @Override
    public String getUuid() {
        Object ref = uuid_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            uuid_ = s;
            return s;
        }
    }

    /**
     * <code>string uuid = 4;</code>
     *
     * @return The bytes for uuid.
     */
    @Override
    public com.google.protobuf.ByteString
    getUuidBytes() {
        Object ref = uuid_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            uuid_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    private byte memoizedIsInitialized = -1;

    @Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (!bytesImg_.isEmpty()) {
            output.writeBytes(1, bytesImg_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(container_)) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 2, container_);
        }
        if (!bytesJson_.isEmpty()) {
            output.writeBytes(3, bytesJson_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(uuid_)) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 4, uuid_);
        }
        unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!bytesImg_.isEmpty()) {
            size += com.google.protobuf.CodedOutputStream
                    .computeBytesSize(1, bytesImg_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(container_)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, container_);
        }
        if (!bytesJson_.isEmpty()) {
            size += com.google.protobuf.CodedOutputStream
                    .computeBytesSize(3, bytesJson_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(uuid_)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, uuid_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @Override
    public boolean equals(final Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof IVApiRequest)) {
            return super.equals(obj);
        }
        IVApiRequest other = (IVApiRequest) obj;

        if (!getBytesImg()
                .equals(other.getBytesImg())) return false;
        if (!getContainer()
                .equals(other.getContainer())) return false;
        if (!getBytesJson()
                .equals(other.getBytesJson())) return false;
        if (!getUuid()
                .equals(other.getUuid())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
    }

    @Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + BYTES_IMG_FIELD_NUMBER;
        hash = (53 * hash) + getBytesImg().hashCode();
        hash = (37 * hash) + CONTAINER_FIELD_NUMBER;
        hash = (53 * hash) + getContainer().hashCode();
        hash = (37 * hash) + BYTES_JSON_FIELD_NUMBER;
        hash = (53 * hash) + getBytesJson().hashCode();
        hash = (37 * hash) + UUID_FIELD_NUMBER;
        hash = (53 * hash) + getUuid().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static IVApiRequest parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static IVApiRequest parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static IVApiRequest parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static IVApiRequest parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static IVApiRequest parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static IVApiRequest parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static IVApiRequest parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static IVApiRequest parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static IVApiRequest parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static IVApiRequest parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static IVApiRequest parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static IVApiRequest parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(IVApiRequest prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
            BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code com.imperialvision.ivapi.IVApiRequest}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:com.imperialvision.ivapi.IVApiRequest)
            IVApiRequestOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Ivapi.internal_static_com_imperialvision_ivapi_IVApiRequest_descriptor;
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Ivapi.internal_static_com_imperialvision_ivapi_IVApiRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            IVApiRequest.class, Builder.class);
        }

        // Construct using com.imperialvision.ivapi.IVApiRequest.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        @Override
        public Builder clear() {
            super.clear();
            bytesImg_ = com.google.protobuf.ByteString.EMPTY;

            container_ = "";

            bytesJson_ = com.google.protobuf.ByteString.EMPTY;

            uuid_ = "";

            return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return Ivapi.internal_static_com_imperialvision_ivapi_IVApiRequest_descriptor;
        }

        @Override
        public IVApiRequest getDefaultInstanceForType() {
            return IVApiRequest.getDefaultInstance();
        }

        @Override
        public IVApiRequest build() {
            IVApiRequest result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @Override
        public IVApiRequest buildPartial() {
            IVApiRequest result = new IVApiRequest(this);
            result.bytesImg_ = bytesImg_;
            result.container_ = container_;
            result.bytesJson_ = bytesJson_;
            result.uuid_ = uuid_;
            onBuilt();
            return result;
        }

        @Override
        public Builder clone() {
            return super.clone();
        }

        @Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return super.setField(field, value);
        }

        @Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return super.addRepeatedField(field, value);
        }

        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof IVApiRequest) {
                return mergeFrom((IVApiRequest) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(IVApiRequest other) {
            if (other == IVApiRequest.getDefaultInstance()) return this;
            if (other.getBytesImg() != com.google.protobuf.ByteString.EMPTY) {
                setBytesImg(other.getBytesImg());
            }
            if (!other.getContainer().isEmpty()) {
                container_ = other.container_;
                onChanged();
            }
            if (other.getBytesJson() != com.google.protobuf.ByteString.EMPTY) {
                setBytesJson(other.getBytesJson());
            }
            if (!other.getUuid().isEmpty()) {
                uuid_ = other.uuid_;
                onChanged();
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        @Override
        public final boolean isInitialized() {
            return true;
        }

        @Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            IVApiRequest parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (IVApiRequest) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private com.google.protobuf.ByteString bytesImg_ = com.google.protobuf.ByteString.EMPTY;

        /**
         * <code>bytes bytes_img = 1;</code>
         *
         * @return The bytesImg.
         */
        @Override
        public com.google.protobuf.ByteString getBytesImg() {
            return bytesImg_;
        }

        /**
         * <code>bytes bytes_img = 1;</code>
         *
         * @param value The bytesImg to set.
         * @return This builder for chaining.
         */
        public Builder setBytesImg(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }

            bytesImg_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>bytes bytes_img = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearBytesImg() {

            bytesImg_ = getDefaultInstance().getBytesImg();
            onChanged();
            return this;
        }

        private Object container_ = "";

        /**
         * <code>string container = 2;</code>
         *
         * @return The container.
         */
        public String getContainer() {
            Object ref = container_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                container_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>string container = 2;</code>
         *
         * @return The bytes for container.
         */
        public com.google.protobuf.ByteString
        getContainerBytes() {
            Object ref = container_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                container_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string container = 2;</code>
         *
         * @param value The container to set.
         * @return This builder for chaining.
         */
        public Builder setContainer(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            container_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string container = 2;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearContainer() {

            container_ = getDefaultInstance().getContainer();
            onChanged();
            return this;
        }

        /**
         * <code>string container = 2;</code>
         *
         * @param value The bytes for container to set.
         * @return This builder for chaining.
         */
        public Builder setContainerBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            container_ = value;
            onChanged();
            return this;
        }

        private com.google.protobuf.ByteString bytesJson_ = com.google.protobuf.ByteString.EMPTY;

        /**
         * <code>bytes bytes_json = 3;</code>
         *
         * @return The bytesJson.
         */
        @Override
        public com.google.protobuf.ByteString getBytesJson() {
            return bytesJson_;
        }

        /**
         * <code>bytes bytes_json = 3;</code>
         *
         * @param value The bytesJson to set.
         * @return This builder for chaining.
         */
        public Builder setBytesJson(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }

            bytesJson_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>bytes bytes_json = 3;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearBytesJson() {

            bytesJson_ = getDefaultInstance().getBytesJson();
            onChanged();
            return this;
        }

        private Object uuid_ = "";

        /**
         * <code>string uuid = 4;</code>
         *
         * @return The uuid.
         */
        public String getUuid() {
            Object ref = uuid_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                uuid_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>string uuid = 4;</code>
         *
         * @return The bytes for uuid.
         */
        public com.google.protobuf.ByteString
        getUuidBytes() {
            Object ref = uuid_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                uuid_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string uuid = 4;</code>
         *
         * @param value The uuid to set.
         * @return This builder for chaining.
         */
        public Builder setUuid(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            uuid_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string uuid = 4;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearUuid() {

            uuid_ = getDefaultInstance().getUuid();
            onChanged();
            return this;
        }

        /**
         * <code>string uuid = 4;</code>
         *
         * @param value The bytes for uuid to set.
         * @return This builder for chaining.
         */
        public Builder setUuidBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            uuid_ = value;
            onChanged();
            return this;
        }

        @Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:com.imperialvision.ivapi.IVApiRequest)
    }

    // @@protoc_insertion_point(class_scope:com.imperialvision.ivapi.IVApiRequest)
    private static final IVApiRequest DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new IVApiRequest();
    }

    public static IVApiRequest getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<IVApiRequest>
            PARSER = new com.google.protobuf.AbstractParser<IVApiRequest>() {
        @Override
        public IVApiRequest parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new IVApiRequest(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<IVApiRequest> parser() {
        return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<IVApiRequest> getParserForType() {
        return PARSER;
    }

    @Override
    public IVApiRequest getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

