// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ivapi.proto

package com.imperialvision.ivapi;

public final class Ivapi {
    private Ivapi() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_imperialvision_ivapi_IVApiRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_com_imperialvision_ivapi_IVApiRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_imperialvision_ivapi_IVApiResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_com_imperialvision_ivapi_IVApiResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_imperialvision_ivapi_Output_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_com_imperialvision_ivapi_Output_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\013ivapi.proto\022\030com.imperialvision.ivapi\"" +
                        "V\n\014IVApiRequest\022\021\n\tbytes_img\030\001 \001(\014\022\021\n\tco" +
                        "ntainer\030\002 \001(\t\022\022\n\nbytes_json\030\003 \001(\014\022\014\n\004uui" +
                        "d\030\004 \001(\t\"\210\001\n\rIVApiResponse\0221\n\007outputs\030\001 \003" +
                        "(\0132 .com.imperialvision.ivapi.Output\022\022\n\n" +
                        "error_code\030\002 \001(\005\022\014\n\004uuid\030\003 \001(\t\022\021\n\tbegint" +
                        "ime\030\004 \001(\t\022\017\n\007endtime\030\005 \001(\t\"q\n\006Output\022\021\n\t" +
                        "res_order\030\001 \001(\005\022\024\n\014bytes_outimg\030\002 \001(\014\022\021\n" +
                        "\tcontainer\030\003 \001(\t\022\r\n\005width\030\004 \001(\005\022\016\n\006heigh" +
                        "t\030\005 \001(\005\022\014\n\004size\030\006 \001(\0032t\n\014IVApiService\022d\n" +
                        "\017getIVApiService\022&.com.imperialvision.iv" +
                        "api.IVApiRequest\032\'.com.imperialvision.iv" +
                        "api.IVApiResponse\"\000B\002P\001b\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_com_imperialvision_ivapi_IVApiRequest_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_com_imperialvision_ivapi_IVApiRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_com_imperialvision_ivapi_IVApiRequest_descriptor,
                new String[]{"BytesImg", "Container", "BytesJson", "Uuid",});
        internal_static_com_imperialvision_ivapi_IVApiResponse_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_com_imperialvision_ivapi_IVApiResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_com_imperialvision_ivapi_IVApiResponse_descriptor,
                new String[]{"Outputs", "ErrorCode", "Uuid", "Begintime", "Endtime",});
        internal_static_com_imperialvision_ivapi_Output_descriptor =
                getDescriptor().getMessageTypes().get(2);
        internal_static_com_imperialvision_ivapi_Output_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_com_imperialvision_ivapi_Output_descriptor,
                new String[]{"ResOrder", "BytesOutimg", "Container", "Width", "Height", "Size",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
