// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ivapi.proto

package com.imperialvision.ivapi;

/**
 * Protobuf type {@code com.imperialvision.ivapi.IVApiResponse}
 */
public final class IVApiResponse extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.imperialvision.ivapi.IVApiResponse)
        IVApiResponseOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use IVApiResponse.newBuilder() to construct.
    private IVApiResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private IVApiResponse() {
        outputs_ = java.util.Collections.emptyList();
        uuid_ = "";
        begintime_ = "";
        endtime_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
            UnusedPrivateParameter unused) {
        return new IVApiResponse();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    private IVApiResponse(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    case 10: {
                        if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                            outputs_ = new java.util.ArrayList<Output>();
                            mutable_bitField0_ |= 0x00000001;
                        }
                        outputs_.add(
                                input.readMessage(Output.parser(), extensionRegistry));
                        break;
                    }
                    case 16: {

                        errorCode_ = input.readInt32();
                        break;
                    }
                    case 26: {
                        String s = input.readStringRequireUtf8();

                        uuid_ = s;
                        break;
                    }
                    case 34: {
                        String s = input.readStringRequireUtf8();

                        begintime_ = s;
                        break;
                    }
                    case 42: {
                        String s = input.readStringRequireUtf8();

                        endtime_ = s;
                        break;
                    }
                    default: {
                        if (!parseUnknownField(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            if (((mutable_bitField0_ & 0x00000001) != 0)) {
                outputs_ = java.util.Collections.unmodifiableList(outputs_);
            }
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return Ivapi.internal_static_com_imperialvision_ivapi_IVApiResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
        return Ivapi.internal_static_com_imperialvision_ivapi_IVApiResponse_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        IVApiResponse.class, Builder.class);
    }

    public static final int OUTPUTS_FIELD_NUMBER = 1;
    private java.util.List<Output> outputs_;

    /**
     * <code>repeated .com.imperialvision.ivapi.Output outputs = 1;</code>
     */
    @Override
    public java.util.List<Output> getOutputsList() {
        return outputs_;
    }

    /**
     * <code>repeated .com.imperialvision.ivapi.Output outputs = 1;</code>
     */
    @Override
    public java.util.List<? extends OutputOrBuilder>
    getOutputsOrBuilderList() {
        return outputs_;
    }

    /**
     * <code>repeated .com.imperialvision.ivapi.Output outputs = 1;</code>
     */
    @Override
    public int getOutputsCount() {
        return outputs_.size();
    }

    /**
     * <code>repeated .com.imperialvision.ivapi.Output outputs = 1;</code>
     */
    @Override
    public Output getOutputs(int index) {
        return outputs_.get(index);
    }

    /**
     * <code>repeated .com.imperialvision.ivapi.Output outputs = 1;</code>
     */
    @Override
    public OutputOrBuilder getOutputsOrBuilder(
            int index) {
        return outputs_.get(index);
    }

    public static final int ERROR_CODE_FIELD_NUMBER = 2;
    private int errorCode_;

    /**
     * <code>int32 error_code = 2;</code>
     *
     * @return The errorCode.
     */
    @Override
    public int getErrorCode() {
        return errorCode_;
    }

    public static final int UUID_FIELD_NUMBER = 3;
    private volatile Object uuid_;

    /**
     * <code>string uuid = 3;</code>
     *
     * @return The uuid.
     */
    @Override
    public String getUuid() {
        Object ref = uuid_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            uuid_ = s;
            return s;
        }
    }

    /**
     * <code>string uuid = 3;</code>
     *
     * @return The bytes for uuid.
     */
    @Override
    public com.google.protobuf.ByteString
    getUuidBytes() {
        Object ref = uuid_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            uuid_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int BEGINTIME_FIELD_NUMBER = 4;
    private volatile Object begintime_;

    /**
     * <code>string begintime = 4;</code>
     *
     * @return The begintime.
     */
    @Override
    public String getBegintime() {
        Object ref = begintime_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            begintime_ = s;
            return s;
        }
    }

    /**
     * <code>string begintime = 4;</code>
     *
     * @return The bytes for begintime.
     */
    @Override
    public com.google.protobuf.ByteString
    getBegintimeBytes() {
        Object ref = begintime_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            begintime_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int ENDTIME_FIELD_NUMBER = 5;
    private volatile Object endtime_;

    /**
     * <code>string endtime = 5;</code>
     *
     * @return The endtime.
     */
    @Override
    public String getEndtime() {
        Object ref = endtime_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            endtime_ = s;
            return s;
        }
    }

    /**
     * <code>string endtime = 5;</code>
     *
     * @return The bytes for endtime.
     */
    @Override
    public com.google.protobuf.ByteString
    getEndtimeBytes() {
        Object ref = endtime_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            endtime_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    private byte memoizedIsInitialized = -1;

    @Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        for (int i = 0; i < outputs_.size(); i++) {
            output.writeMessage(1, outputs_.get(i));
        }
        if (errorCode_ != 0) {
            output.writeInt32(2, errorCode_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(uuid_)) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 3, uuid_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(begintime_)) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 4, begintime_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(endtime_)) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 5, endtime_);
        }
        unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        for (int i = 0; i < outputs_.size(); i++) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(1, outputs_.get(i));
        }
        if (errorCode_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(2, errorCode_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(uuid_)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, uuid_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(begintime_)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, begintime_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(endtime_)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, endtime_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @Override
    public boolean equals(final Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof IVApiResponse)) {
            return super.equals(obj);
        }
        IVApiResponse other = (IVApiResponse) obj;

        if (!getOutputsList()
                .equals(other.getOutputsList())) return false;
        if (getErrorCode()
                != other.getErrorCode()) return false;
        if (!getUuid()
                .equals(other.getUuid())) return false;
        if (!getBegintime()
                .equals(other.getBegintime())) return false;
        if (!getEndtime()
                .equals(other.getEndtime())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
    }

    @Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (getOutputsCount() > 0) {
            hash = (37 * hash) + OUTPUTS_FIELD_NUMBER;
            hash = (53 * hash) + getOutputsList().hashCode();
        }
        hash = (37 * hash) + ERROR_CODE_FIELD_NUMBER;
        hash = (53 * hash) + getErrorCode();
        hash = (37 * hash) + UUID_FIELD_NUMBER;
        hash = (53 * hash) + getUuid().hashCode();
        hash = (37 * hash) + BEGINTIME_FIELD_NUMBER;
        hash = (53 * hash) + getBegintime().hashCode();
        hash = (37 * hash) + ENDTIME_FIELD_NUMBER;
        hash = (53 * hash) + getEndtime().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static IVApiResponse parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static IVApiResponse parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static IVApiResponse parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static IVApiResponse parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static IVApiResponse parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static IVApiResponse parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static IVApiResponse parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static IVApiResponse parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static IVApiResponse parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static IVApiResponse parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static IVApiResponse parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static IVApiResponse parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(IVApiResponse prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
            BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code com.imperialvision.ivapi.IVApiResponse}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:com.imperialvision.ivapi.IVApiResponse)
            IVApiResponseOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Ivapi.internal_static_com_imperialvision_ivapi_IVApiResponse_descriptor;
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Ivapi.internal_static_com_imperialvision_ivapi_IVApiResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            IVApiResponse.class, Builder.class);
        }

        // Construct using com.imperialvision.ivapi.IVApiResponse.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
                getOutputsFieldBuilder();
            }
        }

        @Override
        public Builder clear() {
            super.clear();
            if (outputsBuilder_ == null) {
                outputs_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000001);
            } else {
                outputsBuilder_.clear();
            }
            errorCode_ = 0;

            uuid_ = "";

            begintime_ = "";

            endtime_ = "";

            return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return Ivapi.internal_static_com_imperialvision_ivapi_IVApiResponse_descriptor;
        }

        @Override
        public IVApiResponse getDefaultInstanceForType() {
            return IVApiResponse.getDefaultInstance();
        }

        @Override
        public IVApiResponse build() {
            IVApiResponse result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @Override
        public IVApiResponse buildPartial() {
            IVApiResponse result = new IVApiResponse(this);
            int from_bitField0_ = bitField0_;
            if (outputsBuilder_ == null) {
                if (((bitField0_ & 0x00000001) != 0)) {
                    outputs_ = java.util.Collections.unmodifiableList(outputs_);
                    bitField0_ = (bitField0_ & ~0x00000001);
                }
                result.outputs_ = outputs_;
            } else {
                result.outputs_ = outputsBuilder_.build();
            }
            result.errorCode_ = errorCode_;
            result.uuid_ = uuid_;
            result.begintime_ = begintime_;
            result.endtime_ = endtime_;
            onBuilt();
            return result;
        }

        @Override
        public Builder clone() {
            return super.clone();
        }

        @Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return super.setField(field, value);
        }

        @Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return super.addRepeatedField(field, value);
        }

        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof IVApiResponse) {
                return mergeFrom((IVApiResponse) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(IVApiResponse other) {
            if (other == IVApiResponse.getDefaultInstance()) return this;
            if (outputsBuilder_ == null) {
                if (!other.outputs_.isEmpty()) {
                    if (outputs_.isEmpty()) {
                        outputs_ = other.outputs_;
                        bitField0_ = (bitField0_ & ~0x00000001);
                    } else {
                        ensureOutputsIsMutable();
                        outputs_.addAll(other.outputs_);
                    }
                    onChanged();
                }
            } else {
                if (!other.outputs_.isEmpty()) {
                    if (outputsBuilder_.isEmpty()) {
                        outputsBuilder_.dispose();
                        outputsBuilder_ = null;
                        outputs_ = other.outputs_;
                        bitField0_ = (bitField0_ & ~0x00000001);
                        outputsBuilder_ =
                                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                                        getOutputsFieldBuilder() : null;
                    } else {
                        outputsBuilder_.addAllMessages(other.outputs_);
                    }
                }
            }
            if (other.getErrorCode() != 0) {
                setErrorCode(other.getErrorCode());
            }
            if (!other.getUuid().isEmpty()) {
                uuid_ = other.uuid_;
                onChanged();
            }
            if (!other.getBegintime().isEmpty()) {
                begintime_ = other.begintime_;
                onChanged();
            }
            if (!other.getEndtime().isEmpty()) {
                endtime_ = other.endtime_;
                onChanged();
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        @Override
        public final boolean isInitialized() {
            return true;
        }

        @Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            IVApiResponse parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (IVApiResponse) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private int bitField0_;

        private java.util.List<Output> outputs_ =
                java.util.Collections.emptyList();

        private void ensureOutputsIsMutable() {
            if (!((bitField0_ & 0x00000001) != 0)) {
                outputs_ = new java.util.ArrayList<Output>(outputs_);
                bitField0_ |= 0x00000001;
            }
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<
                Output, Output.Builder, OutputOrBuilder> outputsBuilder_;

        /**
         * <code>repeated .com.imperialvision.ivapi.Output outputs = 1;</code>
         */
        public java.util.List<Output> getOutputsList() {
            if (outputsBuilder_ == null) {
                return java.util.Collections.unmodifiableList(outputs_);
            } else {
                return outputsBuilder_.getMessageList();
            }
        }

        /**
         * <code>repeated .com.imperialvision.ivapi.Output outputs = 1;</code>
         */
        public int getOutputsCount() {
            if (outputsBuilder_ == null) {
                return outputs_.size();
            } else {
                return outputsBuilder_.getCount();
            }
        }

        /**
         * <code>repeated .com.imperialvision.ivapi.Output outputs = 1;</code>
         */
        public Output getOutputs(int index) {
            if (outputsBuilder_ == null) {
                return outputs_.get(index);
            } else {
                return outputsBuilder_.getMessage(index);
            }
        }

        /**
         * <code>repeated .com.imperialvision.ivapi.Output outputs = 1;</code>
         */
        public Builder setOutputs(
                int index, Output value) {
            if (outputsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureOutputsIsMutable();
                outputs_.set(index, value);
                onChanged();
            } else {
                outputsBuilder_.setMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .com.imperialvision.ivapi.Output outputs = 1;</code>
         */
        public Builder setOutputs(
                int index, Output.Builder builderForValue) {
            if (outputsBuilder_ == null) {
                ensureOutputsIsMutable();
                outputs_.set(index, builderForValue.build());
                onChanged();
            } else {
                outputsBuilder_.setMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .com.imperialvision.ivapi.Output outputs = 1;</code>
         */
        public Builder addOutputs(Output value) {
            if (outputsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureOutputsIsMutable();
                outputs_.add(value);
                onChanged();
            } else {
                outputsBuilder_.addMessage(value);
            }
            return this;
        }

        /**
         * <code>repeated .com.imperialvision.ivapi.Output outputs = 1;</code>
         */
        public Builder addOutputs(
                int index, Output value) {
            if (outputsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureOutputsIsMutable();
                outputs_.add(index, value);
                onChanged();
            } else {
                outputsBuilder_.addMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .com.imperialvision.ivapi.Output outputs = 1;</code>
         */
        public Builder addOutputs(
                Output.Builder builderForValue) {
            if (outputsBuilder_ == null) {
                ensureOutputsIsMutable();
                outputs_.add(builderForValue.build());
                onChanged();
            } else {
                outputsBuilder_.addMessage(builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .com.imperialvision.ivapi.Output outputs = 1;</code>
         */
        public Builder addOutputs(
                int index, Output.Builder builderForValue) {
            if (outputsBuilder_ == null) {
                ensureOutputsIsMutable();
                outputs_.add(index, builderForValue.build());
                onChanged();
            } else {
                outputsBuilder_.addMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .com.imperialvision.ivapi.Output outputs = 1;</code>
         */
        public Builder addAllOutputs(
                Iterable<? extends Output> values) {
            if (outputsBuilder_ == null) {
                ensureOutputsIsMutable();
                addAll(
                        values, outputs_);
                onChanged();
            } else {
                outputsBuilder_.addAllMessages(values);
            }
            return this;
        }

        /**
         * <code>repeated .com.imperialvision.ivapi.Output outputs = 1;</code>
         */
        public Builder clearOutputs() {
            if (outputsBuilder_ == null) {
                outputs_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000001);
                onChanged();
            } else {
                outputsBuilder_.clear();
            }
            return this;
        }

        /**
         * <code>repeated .com.imperialvision.ivapi.Output outputs = 1;</code>
         */
        public Builder removeOutputs(int index) {
            if (outputsBuilder_ == null) {
                ensureOutputsIsMutable();
                outputs_.remove(index);
                onChanged();
            } else {
                outputsBuilder_.remove(index);
            }
            return this;
        }

        /**
         * <code>repeated .com.imperialvision.ivapi.Output outputs = 1;</code>
         */
        public Output.Builder getOutputsBuilder(
                int index) {
            return getOutputsFieldBuilder().getBuilder(index);
        }

        /**
         * <code>repeated .com.imperialvision.ivapi.Output outputs = 1;</code>
         */
        public OutputOrBuilder getOutputsOrBuilder(
                int index) {
            if (outputsBuilder_ == null) {
                return outputs_.get(index);
            } else {
                return outputsBuilder_.getMessageOrBuilder(index);
            }
        }

        /**
         * <code>repeated .com.imperialvision.ivapi.Output outputs = 1;</code>
         */
        public java.util.List<? extends OutputOrBuilder>
        getOutputsOrBuilderList() {
            if (outputsBuilder_ != null) {
                return outputsBuilder_.getMessageOrBuilderList();
            } else {
                return java.util.Collections.unmodifiableList(outputs_);
            }
        }

        /**
         * <code>repeated .com.imperialvision.ivapi.Output outputs = 1;</code>
         */
        public Output.Builder addOutputsBuilder() {
            return getOutputsFieldBuilder().addBuilder(
                    Output.getDefaultInstance());
        }

        /**
         * <code>repeated .com.imperialvision.ivapi.Output outputs = 1;</code>
         */
        public Output.Builder addOutputsBuilder(
                int index) {
            return getOutputsFieldBuilder().addBuilder(
                    index, Output.getDefaultInstance());
        }

        /**
         * <code>repeated .com.imperialvision.ivapi.Output outputs = 1;</code>
         */
        public java.util.List<Output.Builder>
        getOutputsBuilderList() {
            return getOutputsFieldBuilder().getBuilderList();
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<
                Output, Output.Builder, OutputOrBuilder>
        getOutputsFieldBuilder() {
            if (outputsBuilder_ == null) {
                outputsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                        Output, Output.Builder, OutputOrBuilder>(
                        outputs_,
                        ((bitField0_ & 0x00000001) != 0),
                        getParentForChildren(),
                        isClean());
                outputs_ = null;
            }
            return outputsBuilder_;
        }

        private int errorCode_;

        /**
         * <code>int32 error_code = 2;</code>
         *
         * @return The errorCode.
         */
        @Override
        public int getErrorCode() {
            return errorCode_;
        }

        /**
         * <code>int32 error_code = 2;</code>
         *
         * @param value The errorCode to set.
         * @return This builder for chaining.
         */
        public Builder setErrorCode(int value) {

            errorCode_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int32 error_code = 2;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearErrorCode() {

            errorCode_ = 0;
            onChanged();
            return this;
        }

        private Object uuid_ = "";

        /**
         * <code>string uuid = 3;</code>
         *
         * @return The uuid.
         */
        public String getUuid() {
            Object ref = uuid_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                uuid_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>string uuid = 3;</code>
         *
         * @return The bytes for uuid.
         */
        public com.google.protobuf.ByteString
        getUuidBytes() {
            Object ref = uuid_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                uuid_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string uuid = 3;</code>
         *
         * @param value The uuid to set.
         * @return This builder for chaining.
         */
        public Builder setUuid(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            uuid_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string uuid = 3;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearUuid() {

            uuid_ = getDefaultInstance().getUuid();
            onChanged();
            return this;
        }

        /**
         * <code>string uuid = 3;</code>
         *
         * @param value The bytes for uuid to set.
         * @return This builder for chaining.
         */
        public Builder setUuidBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            uuid_ = value;
            onChanged();
            return this;
        }

        private Object begintime_ = "";

        /**
         * <code>string begintime = 4;</code>
         *
         * @return The begintime.
         */
        public String getBegintime() {
            Object ref = begintime_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                begintime_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>string begintime = 4;</code>
         *
         * @return The bytes for begintime.
         */
        public com.google.protobuf.ByteString
        getBegintimeBytes() {
            Object ref = begintime_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                begintime_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string begintime = 4;</code>
         *
         * @param value The begintime to set.
         * @return This builder for chaining.
         */
        public Builder setBegintime(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            begintime_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string begintime = 4;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearBegintime() {

            begintime_ = getDefaultInstance().getBegintime();
            onChanged();
            return this;
        }

        /**
         * <code>string begintime = 4;</code>
         *
         * @param value The bytes for begintime to set.
         * @return This builder for chaining.
         */
        public Builder setBegintimeBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            begintime_ = value;
            onChanged();
            return this;
        }

        private Object endtime_ = "";

        /**
         * <code>string endtime = 5;</code>
         *
         * @return The endtime.
         */
        public String getEndtime() {
            Object ref = endtime_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                endtime_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>string endtime = 5;</code>
         *
         * @return The bytes for endtime.
         */
        public com.google.protobuf.ByteString
        getEndtimeBytes() {
            Object ref = endtime_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                endtime_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string endtime = 5;</code>
         *
         * @param value The endtime to set.
         * @return This builder for chaining.
         */
        public Builder setEndtime(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            endtime_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string endtime = 5;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearEndtime() {

            endtime_ = getDefaultInstance().getEndtime();
            onChanged();
            return this;
        }

        /**
         * <code>string endtime = 5;</code>
         *
         * @param value The bytes for endtime to set.
         * @return This builder for chaining.
         */
        public Builder setEndtimeBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            endtime_ = value;
            onChanged();
            return this;
        }

        @Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:com.imperialvision.ivapi.IVApiResponse)
    }

    // @@protoc_insertion_point(class_scope:com.imperialvision.ivapi.IVApiResponse)
    private static final IVApiResponse DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new IVApiResponse();
    }

    public static IVApiResponse getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<IVApiResponse>
            PARSER = new com.google.protobuf.AbstractParser<IVApiResponse>() {
        @Override
        public IVApiResponse parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new IVApiResponse(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<IVApiResponse> parser() {
        return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<IVApiResponse> getParserForType() {
        return PARSER;
    }

    @Override
    public IVApiResponse getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

