// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ivapi.proto

package com.imperialvision.ivapi;

public interface OutputOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.imperialvision.ivapi.Output)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 res_order = 1;</code>
     *
     * @return The resOrder.
     */
    int getResOrder();

    /**
     * <code>bytes bytes_outimg = 2;</code>
     *
     * @return The bytesOutimg.
     */
    com.google.protobuf.ByteString getBytesOutimg();

    /**
     * <code>string container = 3;</code>
     *
     * @return The container.
     */
    String getContainer();

    /**
     * <code>string container = 3;</code>
     *
     * @return The bytes for container.
     */
    com.google.protobuf.ByteString
    getContainerBytes();

    /**
     * <code>int32 width = 4;</code>
     *
     * @return The width.
     */
    int getWidth();

    /**
     * <code>int32 height = 5;</code>
     *
     * @return The height.
     */
    int getHeight();

    /**
     * <code>int64 size = 6;</code>
     *
     * @return The size.
     */
    long getSize();
}
